#!/usr/bin/env node

/**
 * 🦞 ClawDaddy Daemon
 *
 * Plugin Mode: Connects to Figma via ClawDaddy plugin WebSocket
 * No debug port needed, no patching required, no CDP.
 *
 * Security features:
 * - Session token authentication (X-Daemon-Token header)
 * - No CORS headers (blocks cross-origin browser requests)
 * - Host header validation (blocks DNS rebinding)
 * - Idle timeout auto-shutdown (configurable, default 10 minutes)
 */

import { createServer } from 'http';
import { WebSocketServer, WebSocket } from 'ws';
import { readFileSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';

const PORT = parseInt(process.env.DAEMON_PORT) || 3456;
const IDLE_TIMEOUT_MS = parseInt(process.env.DAEMON_IDLE_TIMEOUT) || 10 * 60 * 1000; // Default: 10 minutes

// ============ SECURITY ============

// Load session token (generated by CLI on daemon start)
const TOKEN_FILE = join(homedir(), '.clawdaddy', '.daemon-token');
let SESSION_TOKEN = null;

try {
  SESSION_TOKEN = readFileSync(TOKEN_FILE, 'utf8').trim();
  console.log('[clawdaddy] 🦞 Session token loaded');
} catch {
  console.error('[clawdaddy] ⚠️  WARNING: No session token found. Daemon will reject all requests.');
}

/**
 * Validate request authentication and origin
 * Returns null if valid, or an error string if rejected
 */
function validateRequest(req) {
  // Layer 1: Host header validation (blocks DNS rebinding)
  const host = req.headers.host || '';
  if (!host.match(/^(localhost|127\.0\.0\.1)(:\d+)?$/)) {
    return 'Invalid host header';
  }

  // Layer 2: Session token (blocks unauthorized local processes)
  const token = req.headers['x-daemon-token'];
  if (!SESSION_TOKEN) {
    return 'No session token configured';
  }
  if (token !== SESSION_TOKEN) {
    return 'Invalid or missing token';
  }

  return null; // Valid
}

// ============ IDLE TIMEOUT ============

let lastActivityTime = Date.now();
let idleTimer = null;

function resetIdleTimer() {
  lastActivityTime = Date.now();
  if (idleTimer) clearTimeout(idleTimer);
  idleTimer = setTimeout(() => {
    const idleSecs = Math.round((Date.now() - lastActivityTime) / 1000);
    console.log(`[clawdaddy] 🦞 Idle for ${idleSecs}s — auto-shutting down`);
    shutdown();
  }, IDLE_TIMEOUT_MS);
}

// Start the idle timer immediately
resetIdleTimer();

// ============ PLUGIN MODE ============

// Plugin Client
let pluginWs = null;
let pluginPendingRequests = new Map();
let pluginMsgId = 0;

function isPluginConnected() {
  return pluginWs && pluginWs.readyState === WebSocket.OPEN;
}

async function evalViaPlugin(code) {
  if (!isPluginConnected()) {
    throw new Error('Plugin not connected. Start the ClawDaddy plugin in Figma.');
  }

  return new Promise((resolve, reject) => {
    const id = ++pluginMsgId;
    const timeout = setTimeout(() => {
      pluginPendingRequests.delete(id);
      reject(new Error('Plugin execution timeout (25s)'));
    }, 25000); // 25s timeout to match plugin-side timeout

    pluginPendingRequests.set(id, { resolve, reject, timeout, code });

    try {
      pluginWs.send(JSON.stringify({
        action: 'eval',
        id: id,
        code: code
      }));
    } catch (sendError) {
      clearTimeout(timeout);
      pluginPendingRequests.delete(id);
      reject(new Error(`Plugin send error: ${sendError.message}`));
    }
  });
}


// ============ HTTP SERVER ============

async function handleRequest(req, res) {
  // Reset idle timer on every request
  resetIdleTimer();

  // SECURITY: No CORS headers (blocks all cross-origin browser requests)

  // Block preflight requests (browsers send OPTIONS before cross-origin POST)
  if (req.method === 'OPTIONS') {
    res.writeHead(403, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'CORS preflight rejected' }));
    return;
  }

  // SECURITY: Validate authentication on all routes
  const authError = validateRequest(req);
  if (authError) {
    res.writeHead(403, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Unauthorized: ' + authError }));
    return;
  }

  // Health check
  if (req.url === '/health') {
    const pluginConnected = isPluginConnected();

    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      status: pluginConnected ? 'ok' : 'disconnected',
      mode: 'safe',
      plugin: pluginConnected,
      idleTimeoutMs: IDLE_TIMEOUT_MS
    }));
    return;
  }

  // Execute command
  if (req.url === '/exec' && req.method === 'POST') {
    let body = '';
    req.on('data', chunk => body += chunk);
    req.on('end', async () => {
      try {
        const { action, code } = JSON.parse(body);

        if (action !== 'eval') {
          throw new Error(`Unknown action: ${action}`);
        }

        const result = await evalViaPlugin(code);

        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ result }));
      } catch (error) {
        res.writeHead(500, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ error: error.message }));
      }
    });
    return;
  }

  res.writeHead(404);
  res.end('Not found');
}

// ============ START SERVERS ============

const httpServer = createServer(handleRequest);

// WebSocket server for plugin connections
const wss = new WebSocketServer({ server: httpServer, path: '/plugin' });

wss.on('connection', (ws) => {
  console.log('[clawdaddy] 🦞 Plugin connected');
  pluginWs = ws;
  resetIdleTimer(); // Plugin connection counts as activity

  ws.on('message', (data) => {
    resetIdleTimer(); // Plugin messages count as activity
    try {
      const msg = JSON.parse(data.toString());

      if (msg.type === 'hello') {
        console.log(`[clawdaddy] 🦞 Plugin: ${msg.name || 'ClawDaddy'} v${msg.version || '1.0.0'}`);
      }

      if (msg.type === 'result') {
        const pending = pluginPendingRequests.get(msg.id);
        if (pending) {
          clearTimeout(pending.timeout);
          pluginPendingRequests.delete(msg.id);

          if (msg.error) {
            pending.reject(new Error(msg.error));
          } else {
            pending.resolve(msg.result);
          }
        }
      }

      // Keepalive ping from plugin
      if (msg.type === 'ping') {
        ws.send(JSON.stringify({ type: 'pong' }));
      }

      if (msg.type === 'pong') {
        // Health check response
      }
    } catch (e) {
      console.error('[clawdaddy] Plugin message error:', e);
    }
  });

  ws.on('close', () => {
    console.log('[clawdaddy] Plugin disconnected');
    pluginWs = null;

    // Reject all pending requests
    for (const [id, pending] of pluginPendingRequests) {
      clearTimeout(pending.timeout);
      pending.reject(new Error('Plugin disconnected'));
    }
    pluginPendingRequests.clear();
  });

  ws.on('error', (error) => {
    console.error('[clawdaddy] Plugin WebSocket error:', error.message);
  });
});

httpServer.listen(PORT, '127.0.0.1', () => {
  console.log(`[clawdaddy] 🦞 Daemon running on http://127.0.0.1:${PORT}`);
  console.log(`[clawdaddy] Mode: Plugin only (Safe Mode)`);
  console.log(`[clawdaddy] Idle timeout: ${IDLE_TIMEOUT_MS / 1000}s`);
  console.log(`[clawdaddy] Auth: token required`);
});

// Graceful shutdown
process.on('SIGTERM', shutdown);
process.on('SIGINT', shutdown);

function shutdown() {
  console.log('[clawdaddy] 🦞 Shutting down...');
  if (idleTimer) clearTimeout(idleTimer);
  if (pluginWs) pluginWs.close();
  httpServer.close(() => process.exit(0));
  // Force exit after 3 seconds if graceful shutdown hangs
  setTimeout(() => process.exit(0), 3000);
}
